- name: "install dependencies."
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    state: present
    production: yes

- name: Creates directory
  file:
    path: /home/ubuntu/dist
    state: directory

- name: Transfer backend files cloud server
  copy:
    src: /root/project/backend/dist.tar.gz
    dest: /home/ubuntu

- name: Extract backend and start node server
  shell: |
    cd /home/ubuntu
    tar -xf dist.tar.gz
    rm -rf dist.tar.gz
    cd dist
    npm i
    pm2 start main.js --update-env
